spring:
  application:
    name: task-manager
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: robin
    password: Pa$$w0rd
    url: jdbc:postgresql://192.168.0.129:5432/taskdb
server:
  port: 8080
logging:
  level:
    org:
      springframework:
        data:
          repository : DEBUG

