spring:
  application:
    name: task-manager
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: robin
    password: Pa$$w0rd
    url: jdbc:postgresql://192.168.0.129:5432/taskdb
server:
  port: 8084
logging:
  level:
    org:
      springframework:
        data:
          repository : DEBUG
# application.yml
springdoc:
  api-docs:
    title: Daliy Task
    description: API documentation for Task application
    version: 0.0.1
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka